[package]
name = "achilles"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
directories = "5.0.1"
dotenv = "0.15.0"
env_logger = "0.11.3"
error-stack = "0.4.1"
log = "0.4.21"
ratatui = "0.26.2"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
